version: "3.8"

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: assignment-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=devlopment
      - PORT=3000
      - AUTH_MONGODB_URI=mongodb+srv://aditya22210331:oKiTR2NEiayMpIOV@cluster0.ojgzw.mongodb.net/auth_system_dev?retryWrites=true&w=majority&appName=Cluster0
      - TRANSACTION_MONGODB_URI=mongodb+srv://aditya22210331:oKiTR2NEiayMpIOV@cluster0.ojgzw.mongodb.net/transactionsData?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your_super_secure_production_jwt_secret_key_minimum_32_characters
      - JWT_EXPIRE=7d
      - COOKIE_EXPIRE=7
      - ENABLE_LOGS=true
      - LOG_LEVEL=info
      - LOG_FILE_PATH=./logs/app.log
      - CORS_ORIGINS=http://localhost:3001,http://localhost:3000
    volumes:
      - backend-logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assignment-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  backend-logs:
    driver: local

networks:
  default:
    name: assignment-network
